parameters:
    blend_tutorial_blog.blogcontroller.class: Blend\TutorialBlogBundle\Controller\BlogController

services:
    blend_tutorial_blog.controller:
        class: %blend_tutorial_blog.blogcontroller.class%
        arguments: [@ezpublish.view_manager]
        calls:
            - [ setContainer, [@service_container] ]

    tblog:
        alias: blend_tutorial_blog.controller
