parameters:
#    blend_tutorial_blog.example.class: Blend\TutorialBlogBundle\Example

services:
#    blend_tutorial_blog.example:
#        class: %blend_tutorial_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
